apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-configmap
  labels:
    app: mysql
data:
  mysql_binlog_format.cnf: |
    [mysqlId]
    binlog-format=mixed
  mysql_binlog_file.cnf: |
    [mysqlId]
    binlog-file=mysql.log
