apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:5.6
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: password
          volumeMounts:
            - name: mysql-configmap-volume
              mountPath: /etc/mysql/conf.d
            - name: mysql-binlog-configmap-volume
              mountPath: /etc/mysql/binlog
      volumes:
        - name: mysql-configmap-volume
          configMap:
            name: mysql-configmap
            items:
              - key: mysql_binlog_format.cnf
                path: binlog_format.cnf
        - name: mysql-binlog-configmap-volume
          configMap:
            name: mysql-configmap
            items:
              - key: mysql_binlog_file.cnf
                path: binlog_file.cnf
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  ports:
    - port: 3306
  selector:
    app: mysql
  clusterIP: None

