apiVersion: v1
kind: Pod
metadata:
  name: initContainer
spec:
  initcontainers:
    - name: c1
      image: centos
      command: ["/bin/bash","-c", "sleep 1500"]
      volumeMounts:
        - name: xchange     # this name should match with volumes name decleared as below
          mountPath: "/tmp/xchange"
    - name: c2
      image: centos
      command: ["/bin/bash","-c", "sleep 1500"]
      volumeMounts:
        - name: xchange     # this name should match with volumes name decleared as below
          mountPath: "/tmp/data"
  volumes:
     - name: xchange
       emptyDir: {}